### ISSUE TITLE
loglevel configuration

### ISSUE THREAD

**Issue by laterne** [nanobox-io/nanobox-docker-redis#23]
expose loglevel option of [redis.conf](http://download.redis.io/redis-stable/redis.conf) in the redis options in the boxfile.yaml
```
data.redis:
  image: nanobox/redis:3.0
  config:
    loglevel: 'warning'
```
